apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: myjob
        spec:
          restartPolicy: OnFailure
          containers:
          - name: mycont
            image: luksa/batch-job

