apiVersion: v1
kind: ReplicationController
metadata:
  name: mypod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: development
    spec:
      containers:
        - image: nginx
          name: my-replica-container
          ports:
            - containerPort: 80

